images:
  logo: assets/images/logo_main.png
  logo_svg: assets/images/logo_ph.svg
  social:
    facebook_logo: assets/images/social/facebook-logo.svg
    linkedin_logo: assets/images/social/linkedin-logo.svg
    youtube_logo: assets/images/social/youtube-play-button.svg
    twitter_logo: assets/images/social/twitter-logo.svg
    whatsapp_logo: assets/images/social/whatsapp-logo.svg
  menu: assets/images/menu.svg
  home_cover: assets/images/home-cover.jpg
